export const COUNTRIES = [
  { id: 1, flag: "🇺🇸", name: "United States" },
  { id: 2, flag: "🇨🇦", name: "Canada" },
  { id: 3, flag: "🇬🇧", name: "United Kingdom" },
  { id: 4, flag: "🇦🇺", name: "Australia" },
  { id: 5, flag: "🇮🇳", name: "India" },
  { id: 6, flag: "🇨🇳", name: "China" },
  { id: 7, flag: "🇯🇵", name: "Japan" },
  { id: 8, flag: "🇩🇪", name: "Germany" },
  { id: 9, flag: "🇫🇷", name: "France" },
  { id: 10, flag: "🇮🇹", name: "Italy" },
  { id: 11, flag: "🇪🇸", name: "Spain" },
  { id: 12, flag: "🇧🇷", name: "Brazil" },
  { id: 13, flag: "🇲🇽", name: "Mexico" },
  { id: 14, flag: "🇷🇺", name: "Russia" },
  { id: 15, flag: "🇿🇦", name: "South Africa" },
  { id: 16, flag: "🇰🇷", name: "South Korea" },
  { id: 17, flag: "🇸🇦", name: "Saudi Arabia" },
  { id: 18, flag: "🇦🇷", name: "Argentina" },
  { id: 19, flag: "🇹🇷", name: "Turkey" },
  { id: 20, flag: "🇮🇩", name: "Indonesia" },
  { id: 21, flag: "🇳🇬", name: "Nigeria" },
  { id: 22, flag: "🇵🇰", name: "Pakistan" },
  { id: 23, flag: "🇵🇭", name: "Philippines" },
  { id: 24, flag: "🇳🇱", name: "Netherlands" },
  { id: 25, flag: "🇸🇬", name: "Singapore" },
  { id: 26, flag: "🇨🇭", name: "Switzerland" },
  { id: 27, flag: "🇧🇩", name: "Bangladesh" },
  { id: 28, flag: "🇲🇾", name: "Malaysia" },
  { id: 29, flag: "🇸🇪", name: "Sweden" },
  { id: 30, flag: "🇵🇱", name: "Poland" },
  { id: 31, flag: "🇨🇴", name: "Colombia" },
  { id: 32, flag: "🇹🇭", name: "Thailand" },
  { id: 33, flag: "🇻🇳", name: "Vietnam" },
  { id: 34, flag: "🇦🇪", name: "United Arab Emirates" },
  { id: 35, flag: "🇪🇬", name: "Egypt" },
  { id: 36, flag: "🇳🇴", name: "Norway" },
  { id: 37, flag: "🇮🇱", name: "Israel" },
  { id: 38, flag: "🇬🇷", name: "Greece" },
  { id: 39, flag: "🇵🇹", name: "Portugal" },
  { id: 40, flag: "🇮🇷", name: "Iran" },
  { id: 41, flag: "🇺🇦", name: "Ukraine" },
  { id: 42, flag: "🇨🇿", name: "Czech Republic" },
  { id: 43, flag: "🇷🇴", name: "Romania" },
  { id: 44, flag: "🇭🇺", name: "Hungary" },
  { id: 45, flag: "🇧🇪", name: "Belgium" },
  { id: 46, flag: "🇩🇰", name: "Denmark" },
  { id: 47, flag: "🇫🇮", name: "Finland" },
  { id: 48, flag: "🇮🇪", name: "Ireland" },
  { id: 49, flag: "🇨🇱", name: "Chile" },
  { id: 50, flag: "🇳🇿", name: "New Zealand" },
  { id: 51, flag: "🇵🇪", name: "Peru" },
  { id: 52, flag: "🇪🇨", name: "Ecuador" },
  { id: 53, flag: "🇻🇪", name: "Venezuela" },
  { id: 54, flag: "🇦🇹", name: "Austria" },
  { id: 55, flag: "🇰🇿", name: "Kazakhstan" },
  { id: 56, flag: "🇿🇲", name: "Zambia" },
  { id: 57, flag: "🇿🇼", name: "Zimbabwe" },
  { id: 58, flag: "🇷🇸", name: "Serbia" },
  { id: 59, flag: "🇭🇷", name: "Croatia" },
  { id: 60, flag: "🇱🇰", name: "Sri Lanka" },
];

export type Country = (typeof COUNTRIES)[number];
