export const TOPICS = [
  { id: 1, icon: "📰", label: "General" },
  { id: 2, icon: "🌍", label: "World" },
  { id: 3, icon: "💼", label: "Business" },
  { id: 4, icon: "⚖️", label: "Politics" },
  { id: 5, icon: "🔬", label: "Science" },
  { id: 6, icon: "⚕️", label: "Health" },
  { id: 7, icon: "🎭", label: "Entertainment" },
  { id: 8, icon: "⚽", label: "Sports" },
  { id: 9, icon: "💻", label: "Technology" },
  { id: 10, icon: "🌦️", label: "Weather" },
  { id: 11, icon: "🎨", label: "Art" },
  { id: 12, icon: "🎶", label: "Music" },
  { id: 13, icon: "📚", label: "Books" },
  { id: 14, icon: "🎥", label: "Movies" },
  { id: 15, icon: "📺", label: "TV Shows" },
  { id: 16, icon: "🎮", label: "Gaming" },
  { id: 17, icon: "🚀", label: "Space" },
  { id: 18, icon: "🏛️", label: "History" },
  { id: 19, icon: "📖", label: "Education" },
  { id: 20, icon: "💡", label: "Innovation" },
  { id: 21, icon: "🧘", label: "Wellness" },
  { id: 22, icon: "🏋️", label: "Fitness" },
  { id: 23, icon: "🍽️", label: "Food" },
  { id: 24, icon: "🍷", label: "Beverages" },
  { id: 25, icon: "✈️", label: "Travel" },
  { id: 26, icon: "🚗", label: "Automotive" },
  { id: 27, icon: "🏠", label: "Home & Garden" },
  { id: 28, icon: "👗", label: "Fashion" },
  { id: 29, icon: "🛍️", label: "Shopping" },
  { id: 30, icon: "💰", label: "Finance" },
  { id: 31, icon: "📊", label: "Economy" },
  { id: 32, icon: "👨‍💻", label: "Programming" },
  { id: 33, icon: "🤖", label: "AI & Robotics" },
  { id: 34, icon: "🔗", label: "Blockchain" },
  { id: 35, icon: "📈", label: "Investing" },
  { id: 36, icon: "💳", label: "Cryptocurrency" },
  { id: 37, icon: "🛡️", label: "Cybersecurity" },
];

export type Topic = (typeof TOPICS)[number];
